import { Theme, Container } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import "./globals.css";
import "./theme-config.css";
import AuthProvider from "@/app/auth/Provider";
import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>

      <QueryClientProvider>
          <AuthProvider>
              <Theme appearance="light" accentColor="purple">
                  <NavBar/>
                  <main>
                      <Container px={"5"}>{children}</Container>
                  </main>
                  {/* <ThemePanel /> */}
              </Theme>
          </AuthProvider>
      </QueryClientProvider>
      
      </body>
    </html>
  );
}
